repos:
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
